# Site settings
title: Davey On The Tech
description: >-
  Software Engineer in California writing about software, web dev, and machine learning 
lang: en-US
timezone: Pacific
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/daveyoon64
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: daveyoon64
  bio: >-
    A tech blog about software engineering, web dev, maybe some game dev, and machine learning <a href="https://github.com/daveyoon64" target="_blank" rel="noopener">@github</a>.
  username: username
  email: your-email@email.com
  avatar: /assets/img/avatar.jpg

# Url settings
url: "https://daveyoon64.github.io/"
baseurl:
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-postfiles
